### ISSUE TITLE
Open Facebook Login popup instead of redirecting to login page in the same window

### ISSUE THREAD

**Issue by ghost** [omab/django-social-auth#140]
Thanks a lot for this wonderful libraray. I have a doubt with the current behaviour of my application wrt to facebook connect and I was wondering if you could help me,

Is there a way by which I could open the facebook login page in a new modal window , instead of redirecting user to log in page on the same window and than redirecting him back to the application once he is authorized. I know there is a way of doing that using the javascript sdk but i am looking for server side authorization.

Any help would be greatly appreciated.

**Comment by cliffrwong** [comment]
Hi. I have the popup login window automatically close after login. But I want to update the original window that the user has logged in. Any idea how to send the signal back to the original window? Thanks!
