### ISSUE TITLE
value error: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Camel** [omab/django-social-auth#359]
I have installed django social auth and read through all the steps in the readme, but when I try to access:

/login/facebook/

I get the following error:

ValueError at /login/facebook/
need more than 1 value to unpack
Request Method: GET
Request URL:    http://173.255.234.34:8000/login/facebook/
Django Version: 1.4
Exception Type: ValueError
Exception Value:  
need more than 1 value to unpack
Exception Location: /usr/local/lib/python2.7/dist-packages/django_social_auth-0.6.9-py2.7.egg/social_auth/backends/**init**.py in get_backends, line 756

Any ideas on how to fix this?

**Comment by ashwini-silicus** [comment]
What was the solution for this? I am facing same error. Please update.
