### ISSUE TITLE
Potential Highjacking Vulnerability

### ISSUE THREAD

**Issue by twoolie** [omab/django-social-auth#386]
From the front page of reddit today: [The Most Common OAuth2 Vulnerability](http://homakov.blogspot.com.au/2012/07/saferweb-most-common-oauth2.html)

In this article It describes a way to force associate with someone else's account by sending them a disguised link or picture that causes them to load the callback url with your association code.

From reading the django-social-auth code, it seems we may be vulnerable to this attack.

The Article goes on to say that the best way to mitigate is to set the state parameter to a hash of session id going out, and check it coming back.

Is there any way that we can mitigate this attack within the current pipeline system, or does it require changes to each oauth2 backend?

**Comment by Dutma012** [comment]
[OK](url)
