### ISSUE TITLE
constant_time_compare / Django1.3

### ISSUE THREAD

**Issue by cemkozinoglu** [omab/django-social-auth#483]
Hey,

Even though user manages to successfully login using Facebook, I think the contanct_time_compare method is not working, as when User accepts the Facebook dialog and returns back to the page, Exception gets raised ;

class AuthStateForbidden(AuthException):
    """State parameter is incorrect."""
    def **unicode**(self):
        return u'Wrong state parameter given.'

But once, I go back to the page, i am logged in.. This happens always.

Here is the code when i traced it back in utils.py that causes the problem -- Any thoughts?:

try:
    from django.utils.crypto import constant_time_compare as ct_compare
except ImportError:  # django < 1.4
    def ct_compare(val1, val2):
        if len(val1) != len(val2):
            return False
        result = 0
        for x, y in zip(val1, val2):
            result |= ord(x) ^ ord(y)
        return result == 0

try:
    from django.utils.functional import empty
except ImportError:  # django < 1.4
    empty = None

get_random_string = random_string
constant_time_compare = ct_compare

**Comment by amigo00678** [comment]
I had this issue. Put domain name in nginx and django settings, not IP of server. That error gone.
