### ISSUE TITLE
Handling " Missing unauthorized token" properly

### ISSUE THREAD

**Issue by ustun** [omab/django-social-auth#634]
Using the linkedin api, I sometimes get the following error:

```
 AuthTokenError: Token error: Missing unauthorized token
```

It seems that this is due to following:

```
    unauthed_tokens = self.request.session.get(name) or []
    if not unauthed_tokens:
        raise AuthTokenError(self, 'Missing unauthorized token')
```

But I'm not sure in what circumstances the error occurs. Is this something that should be fixed in social auth (or maybe a better way to handle this case) or should be handling this in my own code via some middleware that catches this? 

I'm not sure why and when this happens, it goes away when I log in and log out of Linkedin.

**Comment by tobias47n9e** [comment]
Does this happen when the session times out? Starting the login process again seems to solve the issue for me. It only happens when I let a tab sit around and return to the page minutes later.

**Comment by lisitsky** [comment]
With which version have you tested?

**Comment by tobias47n9e** [comment]
Current pip version: 0.1
