### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by kakky** [omab/django-social-auth#774]
I was looking for a package of Django supporting OpenID Connect.
But because I could not find, I tried to write based on the class of OAuth 2.0.

https://gist.github.com/kakky/6809432

Thank you for the wonderful package.
I hope the acceleration of OpenID Connect support.

**Comment by tonylampada** [comment]
@kakky Did you have any luck with python-social-auth?

**Comment by kakky** [comment]
@onylampada Please see here.
https://github.com/omab/python-social-auth/issues/300
https://github.com/omab/python-social-auth/issues/477

**Comment by tonylampada** [comment]
Thanks!
