### ISSUE TITLE
sub-domain session

### ISSUE THREAD

**Issue by segalle** [omab/django-social-auth#783]
hi

i'm trying to keep the session when user is entering sub-domain by using
SESSION_COOKIE_DOMAIN = '.localhost:8000'

unfortunately, when i log in using social auth i get the following error message:
AuthStateMissing: Session value state missing.

Thanks!

**Comment by etothepii** [comment]
Is it possible you are using herokuapp.com? if so *.herokuapp.com is blocked by heroku.
