### ISSUE TITLE
AttributeError: 'GoogleAuth' object has no attribute 'do_auth'

### ISSUE THREAD

**Issue by sid24ss** [omab/django-social-auth#786]
Version: 0.7.28

Been stuck on this for ages. I'm trying to follow the example here for [client side authorization](http://django-social-auth.readthedocs.org/en/latest/use_cases.html?highlight=do_auth#client-side-authorization-libraries). I keep getting the AttributeError.

Is this some version incompatibility issue?

**Comment by spixy** [comment]
Hi, so what method should we call in case of OpenId?
