### ISSUE TITLE
I am facing an issue of this

### ISSUE THREAD

**Issue by alishahpakneeds** [omab/django-social-auth#807]
'tuple' object has no attribute 'rsplit'

**Comment by adilberrada** [comment]
Hello,

Did you manage to find the solution. I am facing the same issue ... thanks in advance

**Comment by alishahpakneeds** [comment]
I m now using djangoallauth

**Comment by adilberrada** [comment]
Is it better in some way ? Can you get authenticated user's friends with djangoallauth ?
Do you have any tuto ?

**Comment by alishahpakneeds** [comment]
Not tutorial I done this thing in many days

**Comment by alishahpakneeds** [comment]
I can do from my code

**Comment by adilberrada** [comment]
Hey do you have a separated djangoallauth app in your project ? Because in my project I have 2 apps ("allauth" and "travels"). After logging in, the user is redirect to a template of "travels". In travels view I cannot do a "if user.is_authenticated" could you help me please ?
