### ISSUE TITLE
AttributeError at /login/facebook/ 'tuple' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by adilberrada** [omab/django-social-auth#817]
Hello,

When I click on Facebook link in the home page to authenticate I get this error:

AttributeError at /login/facebook/
'tuple' object has no attribute 'rsplit'

I couldn't find any answer pleaser HELP !

**Comment by ghost** [comment]
which version of django you're using?

**Comment by ghost** [comment]
The problem is that the function **module_member** over _social/utils.py_ is getting the entire authentication backends tuple defined over the **settings.py**

```
def module_member(name):

    print('social > module_member > ', name) # you will se the tuple
    mod, member = name.rsplit('.', 1)
    module = import_module(mod)
    return getattr(module, member)
```

afaik this should receive the correct backend module path, but i don't know how this magic should be done.

**Comment by Alex-Just** [comment]
@adilberrada, you need to post your **settings.py** file. I had a similar error when my **EMAIL_**\* vars inside **settings.py** had unnecessary trailing commas making them tuples instead of plain string vars.
