### ISSUE TITLE
Per site keys and secrets?

### ISSUE THREAD

**Issue by mnaglee** [omab/django-social-auth#818]
I've got a project with multiple sites, and I would like to enable social auth.  Each site would need to have their own keys and secrets for various backends.  Is there a supported method for doing this?  I imagine I could write middleware or a context processor that updates those values in settings, but django documentation discourages this pretty strongly.  Is there a better way?  My searches have not yet turned up anyone attempting this, so I thought I'd cast about for advice before digging in.  Thanks!

**Comment by mauroka** [comment]
Hello, I would like to know if this is possible.
I can see that the issue is closed but I don't know how to accomplish this.
Thanks a lot.
