### ISSUE TITLE
can't use GoogleOAuth2

### ISSUE THREAD

**Issue by gelog93** [omab/django-social-auth#826]
Hello @omab I built a backend with django for mobile client and I use python-social-auth for sign up users and it works for facebook and twitter but fails for google-oauth2. 
I get this error when try to use google-oauth2:

<code>
 {"detail":"{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"usageLimits\",\n    \"reason\": \"dailyLimitExceededUnreg\",\n    \"message\": \"Daily Limit for Unauthenticated
 Use Exceeded. Continued use requires signup.\",\n    \"extendedHelp\": \"https://code.google.com/apis/console\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Daily Limit for Unaut
henticated Use Exceeded. Continued use requires signup.\"\n }\n}\n"}
</code>

I debugged google backend source code in social package and i find it failed on return statement:
<code>
return self.get_json(url, params={
            'access_token': access_token,
            'alt': 'json'
        })
</code>

I don't know why it fails ! have you any idea about this ?

**Comment by alexandcote** [comment]
Do you solve your issue ?

**Comment by mkdk** [comment]
why it was closed?

**Comment by omab** [comment]
Because this library was deprecated on `Aug 29, 2013`
