### ISSUE TITLE
Facebook backend problem

### ISSUE THREAD

**Issue by MaxFriedrichInitPy** [omab/django-social-auth#829]
Hello I'd like to allow users to login/register through facebook. 
Authentication works but backend creates User instance with the combination of first and last name (from Facebook) as a username and no email.
Google oauth2 backend works just fine.

Here are my settings:
FACEBOOK_APP_ID = 'appid'
FACEBOOK_API_SECRET = 'apisecret'
FACEBOOK_EXTENDED_PERMISSIONS = ['email']

SOCIAL_AUTH_CREATE_USERS = True
SOCIAL_AUTH_FORCE_RANDOM_USERNAME = False
SOCIAL_AUTH_DEFAULT_USERNAME = 'socialauth_user'
SOCIAL_AUTH_COMPLETE_URL_NAME = 'socialauth_complete'
SOCIAL_AUTH_ASSOCIATE_URL_NAME = 'socialauth_associate_complete'
LOGIN_ERROR_URL = '/login/error/'
LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_USER_MODEL = 'users.User'
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

My goal is to create user with email or username filled from FB email data.
I can't overcome this.
Can anyone help?

**Comment by scottlow** [comment]
I am running into the exact same issue. It looks like the permissions requested in FACEBOOK_EXTENDED_PERMISSIONS are not being respected.

In the past, I worked on a project that whose auth pipeline was implemented using python-social-auth, and the SOCIAL_AUTH_FACEBOOK_SCOPE setting seemed to work just fine. Not sure what's happening here.

**Comment by geojacobm6** [comment]
@MaxFriedrichInitPy Did you got any solution for this? I'm facing same issue.

**Comment by evcb** [comment]
Same problem here. No information is being retrieved from Facebook at all. Twitter also has a problem but only with the e-mail address.

**Comment by Hagalas** [comment]
From my experience it's Facebook's api fault. They made some changes and I had the same problem with retrieving data from it. Read changelog in docs and check your version of django-social-auth.

**Comment by evcb** [comment]
Yeah, django-social-auth is dead. People should migrate to python-social-auth. I got it working with their code.
