### ISSUE TITLE
Does SOCIAL_AUTH_FACEBOOK_SCOPE still work?

### ISSUE THREAD

**Issue by evcb** [omab/django-social-auth#836]
Facebook is not fetching data from the user profile. Also, twitter doesn't get the user e-mail. 

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'first_name', 'last_name', ]
SOCIAL_AUTH_TWITTER_SCOPE = ['email', ]
FACEBOOK_EXTENDED_PERMISSIONS = ['email']

Printing details in the pipeline, I can see the following:

{'username': u'John Doe', 'fullname': u'John Doe', 'last_name': '', 'email': '', 'first_name': ''}

Looks like Facebook is not sending the information it should.

**Comment by arahman17** [comment]
This do the expected result for me. Hope it helps...

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
'locale': 'ru_RU',
'fields': 'id, name, email, age_range'
}
