### ISSUE TITLE
Instagram login stopped working - Authentication process cancelled

### ISSUE THREAD

**Issue by mevert** [omab/django-social-auth#847]
Hey,

For some reason my Instagram authentication stopped working suddenly a week ago (Facebook and Google authentication still works) and I haven't found any reason why. I even made a new Instagram authentication client and tested with it but got same errors. Any ideas how to fix this problem or suggestions?

**Request URL:**	http://localhost:8000/complete/instagram/?redirect_state=ZelTyjq0xjxwCnaN3zzczvMVsoVIujuk&code=8893b6554c7e4e01a316d6998a11f5c3&state=ZelTyjq0xjxwCnaN3zzczvMVsoVIujuk
**Exception Type:**	AuthCanceled
**Exception Value:**	Authentication process canceled
During handling of the above exception (400 Client Error: Bad Request for url: https://api.instagram.com/oauth/access_token), another exception occurred:

SOCIAL_AUTH_PIPELINE	
('social.pipeline.social_auth.social_details',
 'social.pipeline.social_auth.social_uid',
 'social.pipeline.social_auth.auth_allowed',
 'social.pipeline.social_auth.social_user',
 'social.pipeline.user.get_username',
 'social.pipeline.user.create_user',
 'social.pipeline.social_auth.associate_user',
 'social.pipeline.debug.debug',
 'social.pipeline.social_auth.load_extra_data',
 'social.pipeline.user.user_details',
 'social.pipeline.debug.debug')

**Comment by adamysu** [comment]
@omab I'm experiencing the same issue but see that this issue has been closed -- was there a resolution?

**Comment by mmerchant** [comment]
@omab was this closed because it is fixed? I seem to be running into this issue as well.

**Comment by omab** [comment]
@mmerchant, this issue was closed because this library is no longer supported (for a few years now).
