### ISSUE TITLE
KeyError at /complete/facebook/  ---- 'access_token'

### ISSUE THREAD

**Issue by daya0576** [omab/django-social-auth#856]
Anyone know how to solve this problem? 
Can not fix it for almost a week! Thx a lot.   

> KeyError at /complete/facebook/
'access_token'
Request Method:	GET
Request URL:	http://www.unsw.co/complete/facebook/?redirect_state=Ht71XJD3BRfcQTjOR8y7UKpNnFDQonuh&code=AQCxPovE0LYPTyFVoNXLMbLgBwz-AX2pDWg4Wu2BbxAnamoUwkZuC12BQIZzjFcz7YrG7sINbvlZa3f_6lPjReTHOn77BcmvLqYWzxc5mOD_sYcxNqJXnCRCNYVNyPvRDd8Oz0agHjk7odOz5sFyrKjIjuxXOAJ6MS99Ic_RsPZNiYrWQ5qeszarpNKs8i1bwUma5e6hFmcL7LmF3ZYKf4KdMasSz7CY6SLG_gA89GX-b7QkixEH1FwZEA00nwCP5tsH4GRnk7bbw2iHCBQpOgoiJ8GoS6fLGy6yKmynY__6lIudVxfaMH2dLtV7KTOxdQkonNTBfQwVzZbfkStVk687&state=Ht71XJD3BRfcQTjOR8y7UKpNnFDQonuh
Django Version:	1.8.3
Exception Type:	KeyError
Exception Value:	
'access_token'
Exception Location:	/home/daya0576/.virtualenvs/rango/local/lib/python2.7/site-packages/social_auth/backends/facebook.py in auth_complete, line 145
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.6
Python Path:	
['/var/www',
 '.',
 '',
 '/var/www',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/lib-tk',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/lib-old',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/daya0576/.virtualenvs/rango/local/lib/python2.7/site-packages',
 '/home/daya0576/.virtualenvs/rango/local/lib/python2.7/site-packages/PIL',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/site-packages',
 '/home/daya0576/.virtualenvs/rango/lib/python2.7/site-packages/PIL',
 '/home/daya0576/unsw-it-8543-courses']
Server time:	Fri, 5 May 2017 00:41:14 +100

**Comment by daya0576** [comment]
The authorization suddenly raises this error without changing any code.
It can be produced by visiting http://www.unsw.co/login/facebook/?next=/ 

Thx a lot!

**Comment by Dimitri-Gnidash** [comment]
I am having a similar issues. Is there a resolution?

**Comment by omab** [comment]
This project was marked as `deprecated` on **Aug 29, 2013**

**Comment by sam-rusty** [comment]
Any solution for this issue? @daya0576 did you get any?

**Comment by daya0576** [comment]
Try [Python Social Auth](http://python-social-auth.readthedocs.io/en/latest/), it works perfectly for me.
